version: "3"

services:
    postgres:
        container_name: superheroapi_postgres
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER:     superheroapi
            POSTGRES_PASSWORD: superheroapi
            POSTGRES_DB:       superheroapi
        volumes:
            - ".dbdata:/var/lib/postgresql"
        restart: always

    adminer:
        container_name: superheroapi_adminer
        image: adminer
        depends_on:
            - postgres
        ports:
            - "8080:8080"
        restart: always
